### ISSUE TITLE
How can we get the clock with minutes ? 

### ISSUE THREAD

**Issue by baladkb** [FaiblUG/jQuery-Lcn-Circle-Range-Select#7]
Hi @jfmaeck ,
I'm currently using this plugin, it's useful for us and we have small doubt 
how can we get the clock with minutes, like now we showing 1h,2h,etc but we need like 1.5h,2.5h,etc..
for Your reference here we have added the screenshot,
![12-7-2017 6-02-34 pm](https://user-images.githubusercontent.com/4152211/33715578-115feb92-db79-11e7-83bf-2156bbf33847.png)

please help us,
thanks.

**Comment by jfmaeck** [comment]
Hi @baladkb, I don't think this is possible out of the box right now. You can either create a pull request adding the ability to specify the step size (e.g. "0.5") or you could use the plugin as it is but setting the max value to 24 instead of 12 and then in the update event listener you could display a more human-readable version of the selected value ...

**Comment by baladkb** [comment]
thanks @jfmaeck 👍 we will try(setting the max value to 24 instead of 12).

**Comment by SasiKumar-Ramesh** [comment]
Hi @jfmaeck 
     How can we hide the value inside the clock?. (i.e 9.3h - 6.3h in the above picture)

**Comment by jfmaeck** [comment]
You could use css for example:

```
.circle-range-select-wrapper .values { display: none; }
```

**Comment by SasiKumar-Ramesh** [comment]
Ok @jfmaeck .. I will try it. Thank you..
